check prereqs, jq 1.6, yq 2.x or 3.x
when attempting to use old jq version 1.5
this script gave an error message like:

jq: error (at tmp-pipeline_build.json:202):
Invalid path expression near attempt to access element "inputs" of
{"inputs":[{"branch":"mast...

changing to instead give an error message:

Unexpected prereq 'jq --version' is not 'jq-1.6'

Also, when used with yq version 4.6.3
this script was giving error messages like:

Error: unknown command "write" for "yq"
Run 'yq --help' for usage.

change to instead give error message:

Unexpected prereq 'yq --version' is not 2.x or 3.x

Might add yq 4.x support at a later date.