fix download of classic pipeline on redacted external_api_url (#13)
Due to recent redaction changes to the toolchain apis,
in the downloaded toolchain.yml service
for a pipeline with type:classic
where it used to have a value like:

external_api_url: https://pipeline-service.us-south.devops.cloud.ibm.com
   /pipeline/pipelines/6cbdcf0a-eb77-4525-a9ab-f0939f3d8ca0

it now instead has:

external_api_url: '****'

This toolchain-to-template script was attempting to use
that external_api_url value and failing while downloading
the pipeline, with an error like:

Get classic pipeline content: curl -H "Authorization: $BEARER_TOKEN" -H
"Accept: application/x-yaml"  tmp.old_toolchain.json tmp.service_0.yml
tmp.service_1.yml toolchain_2021-03-05T21-41-10.yml
Error: open 6cbdcf0a-eb77-4525-a9ab-f0939f3d8ca0.yaml: no such file or
directory


Changing to fix the error, by not using the external_api_url
for classic pipeline downloading.